// <auto-generated />
using System;
using ConsoleHostBuilderAndLogTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleHostBuilderAndLogTest.Migrations
{
    [DbContext(typeof(PageAccessLogContext))]
    partial class PageAccessLogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleHostBuilderAndLogTest.Models.PageAccessLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AccessDate");

                    b.Property<string>("Action");

                    b.Property<string>("ActionTest");

                    b.Property<string>("Controller");

                    b.HasKey("ID");

                    b.ToTable("PageAccessLog");
                });
#pragma warning restore 612, 618
        }
    }
}
